apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: 3-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic3tier-api
  template:
    metadata:
      labels:
        app: basic3tier-api
    spec:
      containers:
      - name: api-container
        image: vijayagagla123/basic3tier-api:latest
        ports:
        - containerPort: 80
        env:
        - name: ConnectionStrings__Basic3Tier
          value: "Host=postgres-service.3-tier-app.svc.cluster.local;Port=5432;Database=basic3tier;Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD)"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: 3-tier-app
spec:
  selector:
    app: basic3tier-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
