apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: 3-tier-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic3tier-api
  template:
    metadata:
      labels:
        app: basic3tier-api
    spec:
      containers:
      - name: api-container
        image: vijayagagla123/basic3tier-api:latest
        ports:
        - containerPort: 80
        volumeMounts:
          - name: db-secret-volume
            mountPath: "/etc/secrets"
            readOnly: true
      volumes:
        - name: db-secret-volume
          secret:
            secretName: db-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: 3-tier-app
spec:
  selector:
    app: basic3tier-api
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
