apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: myapp-tls
  namespace: 3-tier-app
spec:
  secretName: myapp-tls
  dnsNames:
  - vijaya.diogohack.shop
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Never   # or Always (default in v1.18+)